server:
  port: ${PORT:0}

spring:
  application:
    name: api-catalog
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      username: usr-catalog-mongo
      password: pwd-catalog-mongo
      database: catalog-dev-mongo
      port: 27017
      host: localhost
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

info:
  application:
    name: api-catalog
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  healthcheck:
    enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j.retry:
  instances:
    retryFindMovie:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException

resilience4j.circuitbreaker:
  instances:
    findMovie:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10